-- ─────────────────────────────────────────────────────────────────────────────
-- PhysioLink — PostgreSQL Schema
-- Run automatically by postgres container on first start via init.d script.
-- ─────────────────────────────────────────────────────────────────────────────

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─── USERS (owned by patient-service) ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    email         VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL CHECK (role IN ('PATIENT', 'PHYSIO')),
    name          VARCHAR(255) NOT NULL,
    phone         VARCHAR(30),
    date_of_birth DATE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─── PATIENTS ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS patients (
    id                 UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    medical_history    TEXT,
    assigned_physio_id UUID REFERENCES users(id) ON DELETE SET NULL,
    emergency_contact  VARCHAR(255)
);

-- ─── EXERCISES ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS exercises (
    id               UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    name             VARCHAR(255)   NOT NULL,
    description      TEXT,
    target_joint     VARCHAR(50)    NOT NULL,
    target_angle_min DOUBLE PRECISION NOT NULL,
    target_angle_max DOUBLE PRECISION NOT NULL,
    target_reps      INTEGER        NOT NULL DEFAULT 10,
    target_sets      INTEGER        NOT NULL DEFAULT 3,
    video_url        VARCHAR(512),
    created_by       UUID           REFERENCES users(id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

-- ─── ROUTINES ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS routines (
    id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    physio_id  UUID         NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    name       VARCHAR(255),
    notes      TEXT,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─── ROUTINE ↔ EXERCISE (join table) ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS routine_exercises (
    routine_id   UUID    NOT NULL REFERENCES routines(id)  ON DELETE CASCADE,
    exercise_id  UUID    NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
    order_index  INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (routine_id, exercise_id)
);

-- ─── SESSION LOGS ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS session_logs (
    id                UUID             PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id        UUID             NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    exercise_id       UUID             NOT NULL REFERENCES exercises(id) ON DELETE RESTRICT,
    reps_completed    INTEGER          NOT NULL DEFAULT 0,
    avg_angle_accuracy DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    session_time      TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    duration_seconds  INTEGER,
    rep_angles        JSONB            NOT NULL DEFAULT '[]'::jsonb
);

-- ─── RECOVERY PLANS (generated by ML service) ────────────────────────────────
CREATE TABLE IF NOT EXISTS recovery_plans (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id       UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    generated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    plan_json        JSONB       NOT NULL,
    progression_notes TEXT,
    red_flags        JSONB       NOT NULL DEFAULT '[]'::jsonb,
    session_log_id   UUID        REFERENCES session_logs(id) ON DELETE SET NULL
);

-- ─── APPOINTMENTS ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS appointments (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id       UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    physio_id        UUID        NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    scheduled_at     TIMESTAMPTZ NOT NULL,
    duration_minutes INTEGER     NOT NULL DEFAULT 30,
    status           VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED'
                        CHECK (status IN ('SCHEDULED','CONFIRMED','COMPLETED','CANCELLED')),
    notes            TEXT,
    video_room_id    VARCHAR(255),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── INDEXES ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_patients_physio        ON patients(assigned_physio_id);
CREATE INDEX IF NOT EXISTS idx_exercises_joint        ON exercises(target_joint);
CREATE INDEX IF NOT EXISTS idx_routines_patient       ON routines(patient_id);
CREATE INDEX IF NOT EXISTS idx_routines_physio        ON routines(physio_id);
CREATE INDEX IF NOT EXISTS idx_session_logs_patient   ON session_logs(patient_id);
CREATE INDEX IF NOT EXISTS idx_session_logs_exercise  ON session_logs(exercise_id);
CREATE INDEX IF NOT EXISTS idx_session_logs_time      ON session_logs(session_time DESC);
CREATE INDEX IF NOT EXISTS idx_recovery_patient       ON recovery_plans(patient_id);
CREATE INDEX IF NOT EXISTS idx_appointments_patient   ON appointments(patient_id);
CREATE INDEX IF NOT EXISTS idx_appointments_physio    ON appointments(physio_id);
CREATE INDEX IF NOT EXISTS idx_appointments_scheduled ON appointments(scheduled_at);

-- ─── UPDATED_AT TRIGGER ───────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TRIGGER set_appointments_updated_at
    BEFORE UPDATE ON appointments
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- ─── DEV SEED DATA ────────────────────────────────────────────────────────────
-- Passwords are plain 'password' — hashed values will be replaced by the
-- auth service at runtime. These rows let you test immediately.
-- BCrypt hash of 'password' (cost 10):
-- $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy

INSERT INTO users (id, email, password_hash, role, name, phone) VALUES
    ('00000000-0000-0000-0000-000000000001',
     'physio@physiolink.dev',
     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
     'PHYSIO', 'Dr. Sarah Chen', '+1-555-0100'),
    ('00000000-0000-0000-0000-000000000002',
     'patient@physiolink.dev',
     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
     'PATIENT', 'John Smith', '+1-555-0200')
ON CONFLICT (id) DO NOTHING;

INSERT INTO patients (id, medical_history, assigned_physio_id) VALUES
    ('00000000-0000-0000-0000-000000000002',
     'Left knee ACL reconstruction (2024). Cleared for progressive rehab.',
     '00000000-0000-0000-0000-000000000001')
ON CONFLICT (id) DO NOTHING;

INSERT INTO exercises
    (id, name, description, target_joint, target_angle_min, target_angle_max, target_reps, target_sets, created_by)
VALUES
    ('10000000-0000-0000-0000-000000000001',
     'Squat', 'Full bodyweight squat targeting knee flexion.',
     'LEFT_KNEE', 70.0, 110.0, 12, 3,
     '00000000-0000-0000-0000-000000000001'),
    ('10000000-0000-0000-0000-000000000002',
     'Knee Extension', 'Seated knee extension for quad strengthening.',
     'LEFT_KNEE', 160.0, 180.0, 15, 3,
     '00000000-0000-0000-0000-000000000001'),
    ('10000000-0000-0000-0000-000000000003',
     'Shoulder Raise', 'Lateral shoulder raise for rotator cuff rehab.',
     'LEFT_SHOULDER', 75.0, 105.0, 12, 3,
     '00000000-0000-0000-0000-000000000001'),
    ('10000000-0000-0000-0000-000000000004',
     'Arm Curl', 'Bicep curl for elbow flexion rehab.',
     'LEFT_ELBOW', 40.0, 70.0, 15, 3,
     '00000000-0000-0000-0000-000000000001'),
    ('10000000-0000-0000-0000-000000000005',
     'Hip Abduction', 'Standing hip abduction for glute/hip stability.',
     'LEFT_HIP', 20.0, 45.0, 12, 3,
     '00000000-0000-0000-0000-000000000001')
ON CONFLICT (id) DO NOTHING;
